CREATE TABLE "otps" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone" varchar,
  "otp" int,
  "time" timestamp,
  "soft_delete" timestamp
);


CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "password" varchar,
  "fcm_token" varchar,
  "time" timestamp,
  "soft_delete" timestamp
);

CREATE TABLE "profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "address" varchar,
  "phone" varchar,
  "phone_verified_at" timestamp,
  "user_id" int,
  "time" timestamp,
  "soft_delete" timestamp
);

ALTER TABLE "profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");